import type { AdminRole } from '@prisma/client';

export const PERMISSIONS = {
  OVERVIEW_READ: 'OVERVIEW_READ',
  ADMISSIONS_READ: 'ADMISSIONS_READ',
  ADMISSIONS_WRITE: 'ADMISSIONS_WRITE',
  FAMILIES_READ: 'FAMILIES_READ',
  FAMILIES_WRITE: 'FAMILIES_WRITE',
  CRM_READ: 'CRM_READ',
  CRM_WRITE: 'CRM_WRITE',
  BILLING_READ: 'BILLING_READ',
  BILLING_WRITE: 'BILLING_WRITE',
  POLICY_WRITE: 'POLICY_WRITE',
  COMMUNICATIONS_READ: 'COMMUNICATIONS_READ',
  COMMUNICATIONS_WRITE: 'COMMUNICATIONS_WRITE',
  SENSITIVE_DATA_READ: 'SENSITIVE_DATA_READ',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const DIRECTOR_SET: Permission[] = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  DIRECTOR: DIRECTOR_SET,
  ADMISSIONS: [
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.ADMISSIONS_READ,
    PERMISSIONS.ADMISSIONS_WRITE,
    PERMISSIONS.FAMILIES_READ,
    PERMISSIONS.FAMILIES_WRITE,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.COMMUNICATIONS_WRITE,
    PERMISSIONS.SENSITIVE_DATA_READ,
  ],
  BILLING: [
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.FAMILIES_READ,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.COMMUNICATIONS_READ,
    PERMISSIONS.COMMUNICATIONS_WRITE,
  ],
  READ_ONLY: [
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.ADMISSIONS_READ,
    PERMISSIONS.FAMILIES_READ,
    PERMISSIONS.CRM_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.COMMUNICATIONS_READ,
  ],
};

export function hasPermission(adminRole: AdminRole | null | undefined, permission: Permission) {
  if (!adminRole) return false;
  return ROLE_PERMISSIONS[adminRole]?.includes(permission) ?? false;
}
